spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  cloud:
    aws:
      credentials:
        access-key: "asdf"
        secret-key: "asdf"
      s3:
        bucket: "asdfasdf"


